[package]
name = "tsp-toolkit-kic-lib"
description = "A library specifically enabling communication to the Keithley product-line of instruments"
version = "0.11.2"
authors = ["Keithley Instruments, LLC"]
edition = "2021"
repository = "https://git.keithley.com/trebuchet/teaspoon/ki-comms"

[dependencies]
bytes = "1.4.0"
phf = { version = "0.11.1", features = ["macros"] }
rpassword = "7.2.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
thiserror = "1.0.38"
tmc = { git = "https://github.com/esarver/rusb-usbtmc" }
tracing = { version = "0.1", features = ["async-await"] }
rusb = "0.9.1"
chrono = "0.4.30"
minidom = "0.15.0"
reqwest = { version = "^0.10", features = ["blocking"] } 
#oklib-rs = { git = "https://git.keithley.com/trebuchet/teaspoon/oklib-rs.git", branch = "main", optional = true }

[dev-dependencies]
anyhow = "1.0.69"
bytes = "1"
colored = "2.0.0"
mockall = { version = "0.11.4", features = ["nightly"] }
